---
title: "Montgomery County, MD Accidents Analysis"
author: "Jeremy Locatelli, Fernando Madrigal"
date: "March 15, 2018"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview
In this project we are analysing car crash data from Montgomery County, MD


## Initial Cleaning
```{r echo = TRUE}
dat = read.csv("C:/Users/olga_/Documents/Crash_Reporting.csv")
## FIXME
## data cleaning goes here - removing low-predictor factors etc
dat$Local.Case.Number = NULL
dat$Report.Number = NULL
dat$Related.Non.Motorist = NULL #REASON: 96 percent of this column has empty strings and we are not using this column
dat$Non.Motorist.Substance.Abuse = NULL 
dat$Off.Road.Description = NULL
dat$Circumstance[dat$Circumstance == "N/A"] = NA
dat$Municipality[dat$Municipality == "N/A"] = NA
dat$Municipality[dat$Municipality == ""] = NA
dat$Collision.Type[dat$Collision.Type == "N/A"] = NA
dat$Weather[dat$Weather == "N/A"] = NA
dat$Surface.Condition[dat$Surface.Condition == "N/A"] = NA
dat$Light[dat$Light == "N/A"] = NA
dat$Traffic.Control[dat$Traffic.Control == "N/A"] = NA
dat$Driver.Substance.Abuse[dat$Driver.Substance.Abuse == "N/A"] = NA
dat$Vehicle.Damage.Extent[dat$Vehicle.Damage.Extent == "N/A"] = NA
dat$Vehicle.Body.Type[dat$Vehicle.Body.Type == "N/A"] = NA
dat$Vehicle.Movement[dat$Vehicle.Movement == "N/A"] = NA

dat$dtime = strptime(as.character(dat$Crash.Date.Time),"%m/%d/%Y %I:%M:%S %p", tz="EST")
```


## Time Analysis

```{r echo = TRUE}
## Crashes by Days of the Week
dayTable = table(dat$dtime$wday)
par(las=2,mfrow=c(1,2))
barplot(dayTable, main ="Crashes: Day of Week (2015-2018)", names.arg = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"),col = "green")
monthTable = table(dat$dtime$mon)
barplot(monthTable, main="Crashes: By Month (2015-2018)",names.arg = month.name)
```

## Crash Occurances by hour: Weekends

```{r }
sun = table(dat$dtime$hour[dat$dtime$wday == 0]) 
sat= table(dat$dtime$hour[dat$dtime$wday == 6])
## Weekends
plot(sat,type = "l", main = "Crashes per hour (weekends)", col = "red", xlab = "Hour",ylab = "number of incidents") 
lines(sun,type = "l", col="green")



```

## Crash Occurances by hour: Weekdays

```{r }
mon = table(dat$dtime$hour[dat$dtime$wday == 1])
tues = table(dat$dtime$hour[dat$dtime$wday == 2])
wed = table(dat$dtime$hour[dat$dtime$wday == 3])
thur = table(dat$dtime$hour[dat$dtime$wday == 4])
fri = table(dat$dtime$hour[dat$dtime$wday == 5])
## Weekdays
plot(tues,type = "l", main = "Crashes per hour (weekdays)", col = "#A7226E", xlab = "Hour",ylab = "number of incidents") 
lines(mon,type = "l", col="#EC2049")
lines(wed,type = "l", col="#F26B38")
lines(thur,type = "l", col="#F7DB4F")
lines(fri,type = "l", col="#2F9599")
##FIXME add a legend this is a mess
```

## Distracted Drivers

```{r }
par(mar=c(4,20,4,4), las = 1) #bottom, left, top, right
y =sort(table(dat$Driver.Distracted.By)/nrow(dat), decreasing = TRUE)
barplot(y,main ="Non Distracted/Distracted Drivers",xlab = "Percentage",xlim=c(0,1),col = "green",las = 2, axes = TRUE,names.arg = row.names(y),cex.names = .75,horiz = TRUE)
```

## Agencies Responding to Different types of Crashes

```{r }
par(mar=c(3,12,3,5), las = 2) #bottom, left, top, right
x = sort(table(dat$Agency.Name[dat$ACRS.Report.Type == "Property Damage Crash"]),decreasing = TRUE)
barplot(x,col = "green",horiz = TRUE,main = "Agencies Responding to Property Damage Crashes")

par(mar=c(3,12,3,5), las = 2) #bottom, left, top, right
x = sort(table(dat$Agency.Name[dat$ACRS.Report.Type == "Injury Crash"]),decreasing = TRUE)
barplot(x,col = "green",horiz = TRUE,main = "Agencies Responding to Injury Crashes")

par(mar=c(3,12,3,5), las = 2) #bottom, left, top, right
x = sort(table(dat$Agency.Name[dat$ACRS.Report.Type == "Fatal Crash"]),decreasing = TRUE)
barplot(x,col = "green",horiz = TRUE,main = "Agencies Responding to Fatal Crashes")
```
